import { gql } from '@apollo/client';
export const QUERY = gql`query listBooksOfUser($userId: Float!, $listOption: ListOptionInputSchema){
    listBooksOfUser(userId: $userId, listOption: $listOption){
        bookList{
            bookId
            bookName
            displayName
            bookCategoryId
            bookCategory{
                bookCategoryId
                parentBookCategoryId
                bookCategoryName
                createdTime
                updatedTime
            }
            subjectId
            subject{
                subjectId
                subjectName
                createdTime
                updatedTime
            }
            isbn
            issn
            pubDate
            pubEdition
            numOfPages
            author
            publisher
            description
            size{
                height
                width
            }
            bookStatus
            contentsAgeTypeId
            contentsAgeType{
                contentsAgeTypeId
                contentsAgeTypeName
                createdTime
                updatedTime
            }
            bookType
            bookTableOfContentsList{
                bookTableOfContentsId
                bookId
                parentBookTableOfContentsId
                order
                tableOfContentsName
                pageName
                createdTime
                updatedTime
            }
            pageList{
                bookId
                pageIndex
                pageId
                pageName
                pageElement{
                    bookId
                    pageIndex
                    lSize{
                        height
                        width
                    }
                    hSize{
                        height
                        width
                    }
                    elementList{
                        elementId
                        elementType
                        elementValue
                        ownerId
                        ownerType
                        size{
                            height
                            width
                        }
                        rectCoords{
                            coords
                            fragmentOrderNumber
                            fragmentCoords{
                                coords
                                fragmentOrderNumber
                            }
                        }
                        createdTime
                        updatedTime
                    }
                    createdTime
                    updatedTime
                }
                createdTime
                updatedTime
            }
            bookUploaderList{
                bookId
                uploaderType
                uploaderId
                createdTime
                updatedTime
            }
            createdTime
            updatedTime
        }
        listLength
    }
}`