import { gql } from '@apollo/client';
export const QUERY = gql`query listSolutions($listOption: ListOptionInputSchema){
    listSolutions(listOption: $listOption){
        listLength
        solutionList{
            solutionId
            bookId
            pageIndex
            solutionName
            answer
            solutionElement{
                solutionId
                text
                lSize{
                    height
                    width
                }
                hSize{
                    height
                    width
                }
                lPageRectCoordsList{
                    columnIndex
                    coords
                    fragmentOrder
                    pageIndex
                }
                hPageRectCoordsList{
                    columnIndex
                    coords
                    fragmentOrder
                    pageIndex
                }
                elementList{
                    elementId
                    elementType
                    elementValue
                    ownerId
                    ownerType
                    size{
                        height
                        width
                    }
                    rectCoords{
                        coords
                        fragmentOrderNumber
                        fragmentCoords{
                            coords
                            fragmentOrderNumber
                        }
                    }
                    createdTime
                    updatedTime
                }
                orderInPage
                createdTime
                updatedTime
            }
            createdTime
            updatedTime
        }
    }
}`