import { gql } from '@apollo/client';
export const QUERY = gql`query listUserBundlesInPackage($userId: Float!, $packageId: String!, $listOption: ListOptionInputSchema){
    listUserBundlesInPackage(userId: $userId, packageId: $packageId, listOption: $listOption){
        userBundleList{
            userId
            quizId
            bundle{
                quizId
                pbQuiz{
                    quizId
                    bookId
                    pageIndex
                    quizName
                    answer
                    score
                    contentsAgeTypeId
                    subjectId
                    quizTypeId
                    quizAnswerTypeId
                    createdTime
                    updatedTime
                }
                pbQuizPaperList{
                    quizPaperId
                    createdTime
                    updatedTime
                }
                pbSolutionList{
                    solutionId
                    solutionName
                    answer
                    createdTime
                    updatedTime
                }
                attachmentList{
                    attachmentId
                    attachmentTypeId
                    createdTime
                    updatedTime
                }
                source{
                    packageId
                    pageId
                    binderId
                    packageIndex
                }
            }
            quizResultList{
                userId
                quizId
                bookId
                packageId
                userAnswer
                correct
                elapsedSeconds
                round
                periodNumber
                createdTime
                updatedTime
            }
            starredQuiz{
                userId
                quizId
                packageId
                createdTime
                updatedTime
            }
            archiveQuiz{
                userId
                quizId
                createdTime
                updatedTime
            }
        }
        listLength
    }
}`